In [6]:
#importing libraries
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv('/content/preprocessed_dataset111.csv')

In [8]:
df

labels                                    cleaned_comment
0           1              user thanks showing appointment today
1           1                                           haha lol
2           1  love waiting num min cab shortage user please ...
3           1  22 super funny quote funnyquotes funnysayings ...
4           1                 goog morning sorrynotsorry morning
...       ...                                                ...
19415       0                                          good read
19416       0  people living condition always remember blesse...
19417       0  winner seungyoon simple rt u save repost edit ...
19418       0  ok concept kravitz passing note magnus julia p...
19419       1                                  life good get one

[19420 rows x 2 columns]

# Encoding Methods

## One Hot Encoding

One Hot Encoding is a method used to convert categorical data into a binary matrix. Each category is represented by a vector with all elements set to 0 except for the position corresponding to that category, which is set to 1.

### Example:
If we have three categories: cat, dog, and fish, they would be represented as:

- cat → [1, 0, 0]
- dog → [0, 1, 0]
- fish → [0, 0, 1]


In [9]:
from sklearn.preprocessing import OneHotEncoder
from keras.preprocessing.text import Tokenizer

# Tokenize text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['cleaned_comment'])
sequences = tokenizer.texts_to_sequences(df['cleaned_comment'])
onehot_results = tokenizer.texts_to_matrix(df['cleaned_comment'], mode='binary')


In [10]:
onehot_results

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from keras.preprocessing.text import Tokenizer

# Load and prepare your dataset
# df = pd.read_csv('your_dataset.csv')
# Ensure df has 'cleaned_comment' and 'label' columns

# Tokenize text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['cleaned_comment'])
onehot_results = tokenizer.texts_to_matrix(df['cleaned_comment'], mode='binary')

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(onehot_results, df['labels'], test_size=0.2, random_state=42)

# Train the Random Forest classifier with reduced size and parallel computation
rf_classifier = RandomForestClassifier(n_estimators=100, max_depth=10, n_jobs=-1, random_state=42)
rf_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = rf_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Test Accuracy: {accuracy * 100:.2f}%')

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))


Test Accuracy: 58.32%
Classification Report:
              precision    recall  f1-score   support

           0       0.57      1.00      0.73      2178
           1       1.00      0.05      0.10      1706

    accuracy                           0.58      3884
   macro avg       0.79      0.53      0.41      3884
weighted avg       0.76      0.58      0.45      3884

Confusion Matrix:
[[2178    0]
 [1619   87]]


### 2. Label Encoder

Label Encoding converts categorical data into numerical labels. Each category is assigned a unique integer. Unlike One Hot Encoding, this method is not suitable for ordinal data as it imposes an artificial ordering.

**Example:**
If we have three categories: cat, dog, and fish, they would be represented as:

- cat → 0
- dog → 1
- fish → 2


In [25]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

# Load and prepare your dataset
# df = pd.read_csv('your_dataset.csv')
# Ensure df has 'cleaned_comment' and 'label' columns

# Tokenize text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['cleaned_comment'])
onehot_results = tokenizer.texts_to_matrix(df['cleaned_comment'], mode='binary')

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(onehot_results, df['labels'], test_size=0.2, random_state=42)

# Train the Random Forest classifier with reduced size and parallel computation
rf_classifier = RandomForestClassifier(n_estimators=100, max_depth=10, n_jobs=-1, random_state=42)
rf_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = rf_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Test Accuracy: {accuracy * 100:.2f}%')

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))


Test Accuracy: 58.32%
Classification Report:
              precision    recall  f1-score   support

           0       0.57      1.00      0.73      2178
           1       1.00      0.05      0.10      1706

    accuracy                           0.58      3884
   macro avg       0.79      0.53      0.41      3884
weighted avg       0.76      0.58      0.45      3884

Confusion Matrix:
[[2178    0]
 [1619   87]]


### 3. TF-IDF

TF-IDF stands for Term Frequency-Inverse Document Frequency. It is a statistical measure used to evaluate the importance of a word in a document relative to a collection of documents (corpus). The TF-IDF score increases proportionally to the number of times a word appears in a document and is offset by the frequency of the word in the corpus.

**Formula:**

**Term Frequency (TF):**
\[ \text{TF}(t, d) = \frac{\text{Number of times term } t \text{ appears in document } d}{\text{Total number of terms in document } d} \]

**Inverse Document Frequency (IDF):**
\[ \text{IDF}(t, D) = \log \left( \frac{\text{Total number of documents } D}{\text{Number of documents containing term } t} \right) \]

**TF-IDF:**
\[ \text{TF-IDF}(t, d, D) = \text{TF}(t, d) \times \text{IDF}(t, D) \]


In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load and prepare your dataset
# df = pd.read_csv('your_dataset.csv')
# Ensure df has 'cleaned_comment' and 'label' columns

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(df['cleaned_comment'], df['labels'], test_size=0.2, random_state=42)

# Convert text data to tf-idf features
vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Train the Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train_tfidf, y_train)

# Predict on the test set
y_pred = rf_classifier.predict(X_test_tfidf)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Test Accuracy: {accuracy * 100:.2f}%')

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))


Test Accuracy: 73.48%
Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.82      0.78      2178
           1       0.73      0.63      0.68      1706

    accuracy                           0.73      3884
   macro avg       0.73      0.72      0.73      3884
weighted avg       0.73      0.73      0.73      3884

Confusion Matrix:
[[1784  394]
 [ 636 1070]]


### 4. Word2Vec

Word2Vec is a two-layer neural network model that processes text by "vectorizing" words, converting them into continuous vector space representations. The primary advantage of Word2Vec is its ability to capture semantic relationships between words.

**Models:**

1. **CBOW (Continuous Bag of Words):**
   - CBOW predicts the target word (center word) from surrounding context words. It is trained by maximizing the probability of the target word given its context.

2. **Skip-gram:**
   - Skip-gram predicts context words (surrounding words) from the target word. It is trained to maximize the probability of context words given the target word.



In [26]:
import pandas as pd
from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# Load and prepare your dataset
# df = pd.read_csv('your_dataset.csv')
# Ensure df has 'cleaned_comment' and 'label' columns

# Tokenize text
df['tokenized_comment'] = df['cleaned_comment'].apply(lambda x: x.split())

# Train Word2Vec model
w2v_model = Word2Vec(sentences=df['tokenized_comment'], vector_size=100, window=5, min_count=1, workers=4)

def get_avg_word2vec(tokens_list, model, vector_size):
    # Function to average word vectors
    vec = np.zeros(vector_size).reshape((1, vector_size))
    count = 0
    for word in tokens_list:
        try:
            vec += model.wv[word].reshape((1, vector_size))
            count += 1
        except KeyError:  # if the word is not in the vocabulary
            continue
    if count != 0:
        vec /= count
    return vec

# Apply Word2Vec to each comment
X_word2vec = np.concatenate([get_avg_word2vec(comment, w2v_model, 100) for comment in df['tokenized_comment']], axis=0)

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_word2vec, df['labels'], test_size=0.2, random_state=42)

# Train the Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = rf_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Test Accuracy: {accuracy * 100:.2f}%')

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))


Test Accuracy: 62.20%
Classification Report:
              precision    recall  f1-score   support

           0       0.62      0.82      0.71      2178
           1       0.62      0.36      0.46      1706

    accuracy                           0.62      3884
   macro avg       0.62      0.59      0.58      3884
weighted avg       0.62      0.62      0.60      3884

Confusion Matrix:
[[1796  382]
 [1086  620]]


### 5. Term Frequency Encoder

Term Frequency (TF) encoding represents the number of times a word appears in a document. Unlike TF-IDF, it does not consider the word's importance in the corpus, but only in the individual document.

**Example:**

In a document:
"the cat sat on the mat."

- The term frequency for "the" would be 2
- The term frequency for "cat" would be 1
- The term frequency for "sat" would be 1
- The term frequency for "on" would be 1
- The term frequency for "mat" would be 1

Each term's frequency indicates how many times it appears in the document.


In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load and prepare your dataset
# df = pd.read_csv('your_dataset.csv')
# Ensure df has 'cleaned_comment' and 'label' columns

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(df['cleaned_comment'], df['labels'], test_size=0.2, random_state=42)

# Convert text data to term frequency features
vectorizer = CountVectorizer(max_features=5000)
X_train_tf = vectorizer.fit_transform(X_train)
X_test_tf = vectorizer.transform(X_test)

# Train the Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train_tf, y_train)

# Predict on the test set
y_pred = rf_classifier.predict(X_test_tf)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Test Accuracy: {accuracy * 100:.2f}%')

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))


Test Accuracy: 72.61%
Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.76      0.76      2178
           1       0.69      0.68      0.68      1706

    accuracy                           0.73      3884
   macro avg       0.72      0.72      0.72      3884
weighted avg       0.73      0.73      0.73      3884

Confusion Matrix:
[[1664  514]
 [ 550 1156]]


# LSTM Model for Sarcasm Detection in YouTube Comments

### Steps:
1. **Import Libraries**: pandas, Keras, scikit-learn.
2. **Load Dataset**: Ensure the DataFrame has 'cleaned_comment' and 'label' columns.
3. **Tokenize Text**: Convert text data into sequences of integers using Keras's Tokenizer.
4. **Pad Sequences**: Ensure uniform input length with pad_sequences.
5. **Encode Labels**: Convert labels to categorical format.
6. **Split Data**: Use train_test_split for training and test sets.
7. **Define Model**:
   - Sequential model
   - Embedding layer
   - LSTM layer
   - Dropout layer
   - Dense output layer
8. **Compile Model**: Use categorical crossentropy loss and Adam optimizer.
9. **Train Model**: Train for 10 epochs with a batch size of 32.
10. **Evaluate Model**: Assess accuracy on the test set.
11. **Make Predictions**: Generate predictions on the test set for further analysis.


In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense, Dropout
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
from keras.optimizers import Adam

# Load and prepare your dataset
# df = pd.read_csv('your_dataset.csv')
# Ensure df has 'cleaned_comment' and 'label' columns

# Tokenize text
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['cleaned_comment'])
sequences = tokenizer.texts_to_sequences(df['cleaned_comment'])

# Pad sequences to ensure uniform input length
max_sequence_length = max(len(seq) for seq in sequences)
X = pad_sequences(sequences, maxlen=max_sequence_length)

# Encode labels
y = to_categorical(df['labels'])

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the model
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1,
                    output_dim=128,
                    input_length=max_sequence_length))
model.add(LSTM(128, return_sequences=False))
model.add(Dropout(0.5))
model.add(Dense(2, activation='softmax'))  # 2 classes: sarcasm or not

# Compile the model
model.compile(loss='categorical_crossentropy',
              optimizer=Adam(learning_rate=0.001),
              metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.1)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {accuracy * 100:.2f}%')

# Predictions (for demonstration purposes)
predictions = model.predict(X_test)


Epoch 1/10
437/437 [==============================] - 58s 124ms/step - loss: 0.5339 - accuracy: 0.7224 - val_loss: 0.4547 - val_accuracy: 0.7819
Epoch 2/10
437/437 [==============================] - 58s 133ms/step - loss: 0.2588 - accuracy: 0.8947 - val_loss: 0.5280 - val_accuracy: 0.7561
Epoch 3/10
437/437 [==============================] - 50s 114ms/step - loss: 0.1186 - accuracy: 0.9509 - val_loss: 0.6798 - val_accuracy: 0.7658
Epoch 4/10
437/437 [==============================] - 46s 106ms/step - loss: 0.0715 - accuracy: 0.9711 - val_loss: 0.8355 - val_accuracy: 0.7516
Epoch 5/10
437/437 [==============================] - 45s 104ms/step - loss: 0.0501 - accuracy: 0.9793 - val_loss: 1.0642 - val_accuracy: 0.7523
Epoch 6/10
437/437 [==============================] - 43s 98ms/step - loss: 0.0402 - accuracy: 0.9839 - val_loss: 1.1668 - val_accuracy: 0.7400
Epoch 7/10
437/437 [==============================] - 49s 112ms/step - loss: 0.0383 - accuracy: 0.9851 - val_loss: 1.2294 - val_acc